{% set name = "fenicsprecice" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/precice/fenics-adapter/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e903d9d941cdf7630c1f76e2854b06f7366b3b4e3455b12e5072d1755de39b26

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - fenics
    - pip
    - python >=3.6
  run:
    - mpi4py
    - numpy >=1.13.3
    - pyprecice >=2.0.0
    - python >=3.6
    - scipy
    - fenics

test:
  commands:
    - export OMPI_MCA_plm=isolated
    - export OMPI_MCA_rmaps_base_oversubscribe=yes
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - python -c "import fenicsprecice"

about:
  home: https://precice.org
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: preCICE-adapter for the open source computing platform FEniCS
  description: |
    preCICE-adapter for the open source computing platform FEniCS. 
    Note: The adapter currently only supports 2D simulations in FEniCS.
  doc_url: https://precice.org/adapter-fenics.html
  dev_url: https://github.com/precice/fenics-adapter

extra:
  recipe-maintainers:
    - IshaanDesai
    - jan-janssen
